Final/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: 'Please enter your email')]
    #[Assert\Email(message: 'The email "{{ value }}" is not a valid email address')]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Length(min: 6, max: 255, minMessage: 'Your name should be at least {{ limit }} characters', maxMessage: 'Your name cannot be longer than {{ limit }} characters')]
    #[Assert\Regex(
        pattern :"/^(?=.*[A-Z])(?=.*\d).+$/",
        message : "Your password must contain at least one uppercase letter and one numeric character"
    )]
    private ?string $password = null;
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Please enter your  name')]
    #[Assert\Regex(
        pattern: '/^[a-zA-Z]+$/',
        message: 'Your Name should contain only alphabetic letters'
    )]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Please enter your last name')]
    #[Assert\Regex(
        pattern: '/^[a-zA-Z]+$/',
        message: 'Your LastName should contain only alphabetic letters'
    )]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_n = null;

    #[ORM\Column(length: 255)]
    private ?string $sexe = null;
    #[ORM\Column(length: 255)]
    private ?string $num_tel = null;
    #[ORM\Column]
    private ?string $ImagePath = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;
   

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Offre::class)]
    private Collection $offres;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Reclamation::class)]
    private Collection $reclamations;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Reponse::class)]
    private Collection $reponses;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Cours::class)]
    private Collection $cours;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Question::class)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Choix::class)]
    private Collection $choixes;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Demande::class)]
    private Collection $demandes;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class)]
    private Collection $commandes;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Service::class)]
    private Collection $services;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Reservation::class)]
    private Collection $reservations;

    #[ORM\Column(type: 'boolean' , options: ['default' => false]) ]
    private $isVerified = false;
    #[ORM\Column(type: 'boolean' , options: ['default' => false]) ]
    private $isBanned = false;

    public function __construct()
    {
        $this->offres = new ArrayCollection();
        $this->reclamations = new ArrayCollection();
        $this->reponses = new ArrayCollection();
        $this->cours = new ArrayCollection();
        $this->questions = new ArrayCollection();
        $this->choixes = new ArrayCollection();
        $this->demandes = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->services = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }
    public function getDateN(): ?\DateTime
    {
        return $this->date_n;
    }

    public function setDateN(\DateTime $date_n): static
    {
        $this->date_n = $date_n;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }
    public function getImagePath(): ?string
    {
        return $this->ImagePath;
    }

    public function setImagePath(string $ImagePath): static
    {
        $this->ImagePath = $ImagePath;

        return $this;
    }
    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(string $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection<int, Offre>
     */
    public function getOffres(): Collection
    {
        return $this->offres;
    }

    public function addOffre(Offre $offre): static
    {
        if (!$this->offres->contains($offre)) {
            $this->offres->add($offre);
            $offre->setIdUser($this);
        }

        return $this;
    }

    public function removeOffre(Offre $offre): static
    {
        if ($this->offres->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getIdUser() === $this) {
                $offre->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reclamation>
     */
    public function getReclamations(): Collection
    {
        return $this->reclamations;
    }

    public function addReclamation(Reclamation $reclamation): static
    {
        if (!$this->reclamations->contains($reclamation)) {
            $this->reclamations->add($reclamation);
            $reclamation->setUser($this);
        }

        return $this;
    }

    public function removeReclamation(Reclamation $reclamation): static
    {
        if ($this->reclamations->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getUser() === $this) {
                $reclamation->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reponse>
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponse $reponse): static
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses->add($reponse);
            $reponse->setUser($this);
        }

        return $this;
    }

    public function removeReponse(Reponse $reponse): static
    {
        if ($this->reponses->removeElement($reponse)) {
            // set the owning side to null (unless already changed)
            if ($reponse->getUser() === $this) {
                $reponse->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cours>
     */
    public function getCours(): Collection
    {

Final/templates/utilisateur/EditProfile.html.twig
{% extends 'baseF.html.twig' %}

 {% block body %}
<div class="container-fluid py-5" style="background-color: white;">
    <div class="container py-5">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-7 text-center">
                <h1 class="mb-4 text-green">Welcome User, You can edit your profile</h1>
            </div>

    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="wow fadeIn" data-wow-delay="0.3s" style="background-color: #fff; border: 1px solid #28a745; border-radius: 5px;">
                <div class="card-body p-4">
                    <a href="{{ path('app_profile', {'id': user.id}) }}"></a>

                    {{ form_start(form, {'attr': {'novalidate': 'novalidate', 'name': 'my-form', 'id': 'my-form'}}) }}

                    <div class="form-group">
                        {{ form_label(form.email, 'Email', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder': 'Enter your email'}}) }}
                        {{ form_errors(form.email) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.nom, 'Name', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.nom, {'attr': {'class': 'form-control', 'placeholder': 'Enter your name'}}) }}
                        {{ form_errors(form.nom) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.prenom, 'LastName', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.prenom, {'attr': {'class': 'form-control', 'placeholder': 'Enter your last name'}}) }}
                        {{ form_errors(form.prenom) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.adresse, 'Address', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.adresse, {'attr': {'class': 'form-control', 'placeholder': 'Enter your Adress'}}) }}
                        {{ form_errors(form.adresse) }}
                    </div>
                     <div class="form-group">
                        {{ form_label(form.num_tel, 'Tel', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.num_tel, {'attr': {'class': 'form-control', 'placeholder': 'Enter your username'}}) }}
                        {{ form_errors(form.num_tel) }}
                    </div>
                      <div class="form-group">
                        {{ form_label(form.sexe, 'Gender', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.sexe, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.sexe) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.ImagePath, 'Image') }}
                        {{ form_widget(form.ImagePath, { 'attr': {'class': 'form-control'} }) }}
                        {% if form_errors(form.ImagePath) %}
                            <div class="text-danger">{{ form_errors(form.ImagePath) }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form_label(form.date_n, 'Date of Birth', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.date_n, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.date_n) }}
                    </div>

                    <div class="text-center mt-4">
                      <button type="submit" class="btn btn-primary btn-lg">{{ button_label|default('Save') }}</button>
<a href="{{ path('app_profile', {'id': app.user.id}) }}" class="btn btn-secondary btn-lg mx-2">Cancel</a>


                    </div>

                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
   {% endblock %}

Final/templates/utilisateur/_delete_form.html.twig
<form method="post" action="{{ path('app_utilisateur_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button class="btn">Delete</button>
</form>

Final/templates/utilisateur/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        <label style="color:white;">{{ form_label(form.nom, 'nom') }}</label>
        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
    </div>

    <div class="form-group">
         <label style="color:white;">{{ form_label(form.prenom, 'Prenom') }}</label>
        {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
         <label style="color:white;">{{ form_label(form.email, 'email') }}</label>
        {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
        <label style="color:white;"> {{ form_label(form.ImagePath, 'Image') }}</label>
        {{ form_widget(form.ImagePath, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
         <label style="color:white;">{{ form_label(form.date_n, 'Date') }}</label>
        {{ form_widget(form.date_n, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
         <label style="color:white;">{{ form_label(form.password, 'Password') }}</label>
        {{ form_widget(form.password, {'attr': {'class': 'form-control'}}) }}
    </div>

    <div class="form-group">
         <label style="color:white;">{{ form_label(form.confirm_password, 'Confirm Password') }}</label>
        {{ form_widget(form.confirm_password, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
         <label style="color:white;">{{ form_label(form.adresse, 'Adresse') }}</label>
        {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
        <label style="color:white;"> {{ form_label(form.num_tel, 'Tel') }}</label>
        {{ form_widget(form.num_tel, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
         <label style="color:white;">{{ form_label(form.sexe, 'Sexe') }}</label>
        {{ form_widget(form.sexe, {'attr': {'class': 'form-control'}}) }}
    </div>

    <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Final/templates/utilisateur/edit.html.twig
{% extends 'baseB.html.twig' %}

{% block content %}
    <h1>Edit Utilisateur</h1>

    {{ include('utilisateur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_utilisateur_index') }}">back to list</a>

    {{ include('utilisateur/_delete_form.html.twig') }}
{% endblock %}

Final/templates/utilisateur/editPassFront.html.twig
{% extends 'baseF.html.twig' %}

 {% block body %}
<section>
    <!-- Full Screen Search End -->
<div class="container-fluid py-5" style="background-color: white;">
    <div class="container py-5">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-7 text-center">
                <h1 class="mb-4 text-green">Change your password please !</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="wow fadeIn" data-wow-delay="0.3s" style="background-color: #fff; border: 1px solid #28a745; border-radius: 5px;">
                    <div class="card-body p-4">
                          <form  method="POST" action="{{ path('edit_password_db_front', {'id': user.id}) }}" >
                        
                            <div class="mb-3">
                                 
              
                             {% for flashMessage in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ flashMessage }}
    </div>
{% endfor %}
        <label for="old-password" class="form-label">Old Password</label>
        <input type="password" id="old-password" name="old-password" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">New Password</label>
        <input type="password" id="password" name="password" class="form-control" required pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$" title="Password must contain at least one lowercase, one uppercase, one number, and be at least 8 characters long">
    </div>
    <div class="mb-3">
        <label for="confirmPassword" class="form-label">Confirm Password</label>
        <input type="password" id="confirmPassword" name="confirmPassword" class="form-control" required>
        <div id="passwordMatchError" class="text-danger" style="display: none;">Passwords do not match.</div>
    </div>
                             <div class="text-center mt-4">
                        <div class="text-center mt-4">
                      <button type="submit" class="btn btn-primary btn-lg">{{ button_label|default('Save') }}</button>
<a href="{{ path('app_profile', {'id': app.user.id}) }}" class="btn btn-secondary btn-lg mx-2">Cancel</a>
                    </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
        // Function to validate if the two passwords match
        function validatePassword() {
            var password = document.getElementById("password").value;
            var confirmPassword = document.getElementById("confirmPassword").value;

            if (password !== confirmPassword) {
                document.getElementById("passwordMatchError").style.display = "block";
                return false;
            } else {
                document.getElementById("passwordMatchError").style.display = "none";
                return true;
            }
        }

        // Attach the validation function to the form submission event
        document.querySelector("form").addEventListener("submit", function(event) {
            if (!validatePassword()) {
                event.preventDefault(); // Prevent form submission if passwords don't match
            }
        });
    </script>
    </section>
{% endblock %}

Final/templates/utilisateur/index.html.twig
{% extends 'baseB.html.twig' %}

{% block search %}
 <form method="POST" action="{{path('app_search')}}" class="d-none d-md-flex ms-4">
                    <input class="form-control bg-dark border-0" name="search" type="text" placeholder="Search">
                </form>
{% endblock %}

{% block content %}
 <!-- Sale & Revenue Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-line fa-3x text-primary"></i>
                            <div class="ms-3">
                                <p class="mb-2">Total Users</p>
                                <h6 class="mb-0">{{utilisateurs|length}}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-bar fa-3x text-primary"></i>
                            <div class="ms-3">
                                <p class="mb-2">Total Freelancers</p>
                                <h6 class="mb-0">{{freelancers|length}}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-area fa-3x text-primary"></i>
                            <div class="ms-3">
                                <p class="mb-2">Total Admins</p>
                                <h6 class="mb-0">{{admins|length}}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-pie fa-3x text-primary"></i>
                            <div class="ms-3">
                                <p class="mb-2">Total Clients</p>
                                <h6 class="mb-0">{{clients|length}}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sale & Revenue End -->


            <!-- Sales Chart Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-secondary text-center rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">Accounts creation rate</h6>
                                <a href="">Show All</a>
                            </div>
                            <canvas id="worldwide-sales"></canvas>
                        </div>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-secondary text-center rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">Freelancers per Client</h6>
                                <a href="">Show All</a>
                            </div>
                            <canvas id="salse-revenue" height="100" width="100"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sales Chart End -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  // Bar chart
  var ctx1 = document.getElementById('worldwide-sales').getContext('2d');
  var chart1 = new Chart(ctx1, {
    type: 'bar',
    data: {
      labels: ['Admins', 'Freelancers','Clients'],
      datasets: [{
        label: 'Types',
        backgroundColor: ['rgba(255, 99, 132, 0.2)', 'rgba(54, 162, 235, 0.2)'],
        borderColor: ['rgba(255, 99, 132, 1)', 'rgba(54, 162, 235, 1)'],
        borderWidth: 1,
        data: [{{ admins|length }}, {{ freelancers|length }},{{clients|length}}]
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true,
            fontColor: '#ccc'
          },
          gridLines: {
            color: '#ccc'
          }
        }],
        xAxes: [{
          ticks: {
            fontColor: '#ccc'
          },
          gridLines: {
            color: '#ccc'
          }
        }]
      },
      legend: {
        labels: {
          fontColor: '#ccc'
        }
      }
    }
  });
   var ctx2 = document.getElementById('salse-revenue').getContext('2d');
  var chart2 = new Chart(ctx2, {
    type: 'pie',
    data: {
      labels: ['Clients', 'Freelancers'],
      datasets: [{
        label: 'Number',
         backgroundColor: ['#d9534f', '#f0ad4e'],
        borderColor: '#fff',
         data: [{{ clients|length }}, {{ freelancers|length }}]
      }]
    },
    options: {
      title: {
        display: true,
        text: 'Clients vs Freelancers',
        fontColor: '#ccc'
      },
      legend: {
        labels: {
          fontColor: '#ccc'
        }
        
      }
      
    },width: 50,
    height: 50
  });
</script>

            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Users List</h6>
                        <a href="">Show All</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                                <tr class="text-white">
                                    <th scope="col"><input class="form-check-input" type="checkbox"></th>
                                  
             
    
                <th scope="col">Nom</th>
                <th scope="col">Prenom</th>
                <th scope="col">Image</th>
                <th scope="col">Email</th>
                <th scope="col">Date_n</th>
                <th scope="col">Sexe</th>
                <th scope="col">Num_tel</th>
                <th scope="col">Role</th>
                <th scope="col">Adresse</th>
                 <th scope="col">Banned</th>
                <th scope="col">Verified</th>
                <th scope="col">actions</th>
                                </tr>
                            </thead>
                            <tbody>
                              {% for utilisateur in utilisateurs %}
                                <tr>
                                  <td scope="col"><input class="form-check-input" type="checkbox"></td>
                <td>{{ utilisateur.nom }}</td>
                <td>{{ utilisateur.prenom }}</td>
                <td><img src="{{asset(utilisateur.ImagePath)}}" height="100" width="120"/> </td>
                <td>{{ utilisateur.email }}</td>
                <td>{{ utilisateur.dateN ? utilisateur.dateN|date('Y-m-d') : '' }}</td>
                <td>{{ utilisateur.sexe }}</td>
                <td>{{ utilisateur.numTel }}</td>
                <td>{{ utilisateur.role }}</td>
                <td>{{ utilisateur.adresse }}</td>
                 <td>{% if utilisateur.isBanned == 1 %}<span class="badge bg-danger">Yes{% else %}<span class="badge bg-success">No{% endif %}</td>
                    <td>{% if utilisateur.IsVerified == 1 %}<span class="badge bg-success">Yes{% else %}<span class="badge bg-danger">No{% endif %}</td>
              
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('app_utilisateur_show', {'id': utilisateur.id}) }}">show</a>
                    <a class="btn btn-sm btn-primary" href="{{ path('app_utilisateur_edit', {'id': utilisateur.id}) }}">edit</a>
                    <hr>
                  {% if utilisateur.isBanned == 0 %}
    <a href="{{ path('app_user_ban', {'id': utilisateur.id}) }}" class="btn btn-danger btn-sm rounded-pill py-1 px-3"
       onclick="return confirm('Are you sure you want to ban this user?');">
        <i class="fas fa-ban mr-2"></i>Ban User
    </a>
{% endif %}

{% if utilisateur.isBanned == 1 %}
    <a href="{{ path('app_user_unban', {'id': utilisateur.id}) }}" class="btn btn-danger btn-sm rounded-pill py-1 px-3"
       onclick="return confirm('Are you sure you want to unban this user?');">
        <i class="fas fa-ban mr-2"></i>Unban User
    </a>
{% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
                    </div>
                </div>
            </div>
            <!-- Recent Sales End -->


            <!-- Widgets Start -->
            
            <!-- Widgets End -->

 
              

  
{% endblock %}

Final/templates/utilisateur/new.html.twig
<!DOCTYPE html>

<title>New Utilisateur</title>

{% block body %}
    <h1>Create new Utilisateur</h1>

    {{ include('utilisateur/_form.html.twig') }}

    <a href="{{ path('app_utilisateur_index') }}">back to list</a>
{% endblock %}

Final/templates/utilisateur/thanksEditPass.html.twig
{% extends 'baseF.html.twig' %}
{% block body %}

    <div class="custom-container">
        <div class="col-md-4">
            <div class="border border-3 border-success"></div>
            <div class="card bg-white shadow p-5">
                <div class="mb-4 text-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="text-success" width="75" height="75" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                        <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                    </svg>
                </div>
                <div class="text-center">
                    <h1>Thank You</h1>
                    <p>Your Password has been successfully updated!</p>
                    <a href="{{ path('app_profile', {'id': app.user.id}) }}" class="btn btn-outline-success">Back to Profile</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}